# Generated by Django 2.1.1 on 2019-07-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='adoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image2', models.ImageField(upload_to='images/')),
                ('description3', models.CharField(max_length=10000)),
            ],
        ),
    ]
