# Generated by Django 2.1.1 on 2019-07-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_adoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description3', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='adoption',
        ),
    ]
